Salesforce/deploy/main/default/objects/Demo__e/Demo__e.object-meta.xml
<CustomObject>
    <label>Demo</label>
    <pluralLabel>Demos</pluralLabel>
</CustomObject>

Salesforce/deploy/main/default/objects/Demo__e/fields/fromId__c.field-meta.xml
<CustomField>
    <fullName>fromId__c</fullName>
    <label>From Id</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/deploy/main/default/objects/Demo__e/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/deploy/main/default/objects/Demo__e/fields/private__c.field-meta.xml
<CustomField>
    <fullName>private__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Private</label>
    <type>Checkbox</type>
</CustomField>

Salesforce/deploy/main/default/objects/Demo__e/fields/toId__c.field-meta.xml
<CustomField>
    <fullName>toId__c</fullName>
    <label>To Id</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce/deploy/main/default/objects/Demo__e/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce/deploy/main/default/classes/Publisher.cls
public class Publisher {
	@AuraEnabled
	public static void publish(String channel, String type, Integer fromId, Integer toId, String msg, Integer numberClients) {
		if (channel == '/event/Demo__e') {
			List<Demo__e> demoEvents = new List<Demo__e>();
			if (toId == -1) {
				for (Integer i = 1; i <= numberClients; i++) {
					demoEvents.add(createEvent(channel, type, fromId, i, msg, false));
				}
			} else {
				demoEvents.add(createEvent(channel, type, fromId, toId, msg, true));
			}
			List<Database.SaveResult> results = EventBus.publish(demoEvents);
			// Inspect publishing result for each event
			for (Database.SaveResult sr : results) {
				if (sr.isSuccess()) {
					System.debug('Successfully published event.');
				} else {
					for (Database.Error err : sr.getErrors()) {
						System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
					}
				}
			}
		}
	}

	private static Demo__e createEvent(String channel, String type, Integer fromId, Integer toId, String msg, Boolean isPrivate) {
		Demo__e d = new Demo__e();
		d.type__c = type;
		d.fromId__c = fromId;
		d.toId__c = toId;
		d.message__c = msg;
		d.private__c = isPrivate;
		System.debug(d);
		return d;
	}
}